-- 1. AMPLIACIÓN DE PERFILES DE USUARIO (SISTEMA)
ALTER TABLE user_profiles 
ADD COLUMN IF NOT EXISTS full_name TEXT,
ADD COLUMN IF NOT EXISTS phone TEXT,
ADD COLUMN IF NOT EXISTS address TEXT;

-- 2. RECARGAR EL CACHÉ DEL SCHEMA DE SUPABASE
NOTIFY pgrst, 'reload schema';
