-- 1. AMPLIACIÓN DE DATOS CORPORATIVOS
ALTER TABLE companies 
ADD COLUMN IF NOT EXISTS address TEXT,
ADD COLUMN IF NOT EXISTS contact_person TEXT,
ADD COLUMN IF NOT EXISTS representative_phone TEXT;

-- 2. RECARGAR EL CACHÉ DEL SCHEMA DE SUPABASE
NOTIFY pgrst, 'reload schema';
