-- 1. ADICIÓN DE CAMPOS BÁSICOS A LA TABLA DE EMPLEADOS
ALTER TABLE employees 
ADD COLUMN IF NOT EXISTS cedula TEXT,
ADD COLUMN IF NOT EXISTS address TEXT,
ADD COLUMN IF NOT EXISTS join_date DATE DEFAULT CURRENT_DATE,
ADD COLUMN IF NOT EXISTS emergency_contact TEXT,
ADD COLUMN IF NOT EXISTS emergency_phone TEXT;

-- 2. RECARGAR EL CACHÉ DEL SCHEMA DE SUPABASE PARA DETECTAR LOS CAMBIOS
NOTIFY pgrst, 'reload schema';
