-- 1. ASEGURAR QUE LA COLUMNA MODEL EXISTA EN fleet_vehicles
ALTER TABLE fleet_vehicles ADD COLUMN IF NOT EXISTS model TEXT;

-- 2. RECARGAR EL CACHÉ DEL SCHEMA DE SUPABASE PARA DETECTAR EL CAMBIO
NOTIFY pgrst, 'reload schema';
