-- 1. ASEGURAR QUE TODAS LAS COLUMNAS EXISTAN (por si la tabla ya existía)
ALTER TABLE companies ADD COLUMN IF NOT EXISTS rnc TEXT;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS phone TEXT;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS credit_limit DECIMAL(12,2) DEFAULT 0.00;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS current_balance DECIMAL(12,2) DEFAULT 0.00;

-- 2. RECARGAR EL CACHÉ DEL SCHEMA DE SUPABASE
NOTIFY pgrst, 'reload schema';
